### ISSUE TITLE
Failed to connect to media driver

### ISSUE THREAD

**Issue by EwanValentine** [lirm/aeron-go#34]
First of all, I apologise if this is the wrong place to raise this issue, but any help would be greatly appreciated.

I have the following docker compose file:
```yaml
version: "3.8"

services:
  media-driver:
    container_name: media-driver
    restart: always
    shm_size: 128M
    network_mode: host
    command: >
      "-Daeron.sample.ping.channel=aeron:udp?endpoint=service:40124 \
       -Daeron.sample.pong.channel=aeron:udp?endpoint=media-driver:40123 \
       io.aeron.samples.Ping"
    environment:
      - USER=ewanvalentine
    image: registry.gitlab.com/neomantra/oss/aeron/cpp-debian:master
    volumes:
      - ./dev/:/dev/shm/

  service:
    container_name: service
    restart: always
    build: .
    network_mode: host
    environment:
      - USER=ewanvalentine
    volumes:
      - ./dev/:/dev/shm/
```

And I'm using one of the examples from this repo, but I'm getting the error:
`Failed to connect to media driver: aeron cnc file version not understood: version=512`

Just wondered if you'd seen this previously? Thanks!
